--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2024. 02. 11. 17:21:26
-- Server version: 5.5.5-10.4.32-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO webshop.felhasználók(Azonosító, `E-mail`, Vezetéknév, Keresztnév, Telefonszám, Jelszó, `2fa`, GDPR, SZIránytószám, SZTelepülés, SZLakcím, SZEmelet, SZAjtó, `Bankkártya szám`, Lejárat) VALUES
('U0002', NULL, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, NULL, 0, NULL, '1234567810111213', NULL),
('U0001', NULL, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, NULL, 0, NULL, NULL, NULL),
('A0004', NULL, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, NULL, 0, NULL, NULL, NULL),
('A0002', NULL, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, NULL, 0, NULL, NULL, NULL),
('A0001', NULL, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, NULL, 0, NULL, NULL, NULL),
('A0003', NULL, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, NULL, 0, NULL, NULL, NULL),
('U0003', NULL, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, NULL, 0, NULL, NULL, NULL);