--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2024. 03. 22. 21:59:56
-- Server version: 5.5.5-10.4.32-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO webshop.users(felhasznalo_id, username, lastname, firstname, email, pwd, defaddress, Szállítási_cím, tel, Bankkártya_szám, CVC, lejárat, Regisztráció_ideje, admin, tos) VALUES
(1, 'Testing', 'Doe', 'John', 'asdasd@gmail.com', '$2a$12$jhFTJO4kIP77chUm0V.GzOlG.E5Y1sShuuY4p.2mYb5dCJskRcNn2', '9021, Győr Valami utca', NULL, '+36905683237', NULL, NULL, NULL, '2024-03-21 16:29:12', 0, 0),
(5, 'Cziperlan', 'Czipri', 'Gergő', 'czippgergo@gmail.com', '$2y$12$keYHNueLxnkru5hjhJrd1ud4iaFba.om2wkcHkJWZiFg/hUddIfbC', '9021, Győr Igen Igen', NULL, '+36 40 783 2849', NULL, NULL, NULL, '2024-03-22 20:27:33', 0, 1);